title: One Page Wonder - Jekyll
description: Mike & Becca
sitename: Mike & Becca
baseurl:
sass:
  sass_dir: /assets/_sass
  style: :compressed
collections:
  - features
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE.txt
  - CNAME